services:
  postgres:
    container_name: recsys-postgres
    image: postgres:16.8
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]  # Use $VAR directly
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    container_name: recsys-minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./shared_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  mlflow:
    container_name: recsys-mlflow
    build:
      context: ./mlflow/
      dockerfile: Dockerfile.mlflow
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow_db 
      --default-artifact-root s3://mlflow 
      --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
  
  backend:
    container_name: recsys-backend
    build:
      context: ./backend/
    restart: always
    depends_on:
      - postgres
      - minio
      - mlflow
    ports:
     - "5556:5556"

volumes:
  postgres_data:
  shared_data: