s3:
  endpoint_url: "http://localhost:9000"
  access_key: "admin"
  secret_key: "password"
  bucket_name: "images"

db:
  uri: "postgresql+psycopg2://backend:backend@localhost:5432/app_db"

model:
  url: "http://localhost:5555"